/*
 * enum_cmd.h
 *
 * Created: 26.10.2016 13:11:43
 *  Author: TOE
 */


#ifndef ENUM_CMD_H_
#define ENUM_CMD_H_

/*
 * AT Command IDs.
 *
 * Commands are enumerated, starting with -1 and packed to save memory.
 * Please sort new commands for binary search parser
 */

typedef enum
{
	NO_AT_CMD = 0,

	AT_pC,					// %C
	AT_pV,					// PERCENT VOLTAGE

	AT_A1,					// END DEVICE ASSOCIATIO
	AT_A2,					// COORDINATOR ASSOCIATI
	AT_AC,					// APPLY CHANGES
	AT_AI,					// ASSOCIATION INDICATIO
	AT_AP,					// AP ENABLE

	AT_BD,					// INTERFACE DATA RATE

	AT_CA,					// CCA TRESHOLD
	AT_CC,					// COMMAND SEQUENCE CHAR
	AT_CE,					// COORDINATOR ENABLE
	AT_CH,					// CHANNEL
	AT_CN,					// COMMAND NULL
	AT_CT,					// AT CMD TIMEOUT

	AT_D0,					// DIO0 CONFIGURATION
	AT_D1,					// DIO1 CONFIGURATION
	AT_D2,					// DIO2 CONFIGURATION
	AT_D3,					// DIO3 CONFIGURATION
	AT_D4,					// DIO4 CONFIGURATION
	AT_D5,					// DIO5 CONFIGURATION
	AT_D6,					// DIO6 CONFIGURATION
	AT_D7,					// DIO7 CONFIGURATION
	AT_D8,					// DIO8 CONFIGURATION
	AT_DB,					// RECEIVED SIGNAL STRENGTH
	AT_DD,					// DEVICE TYPE IDENTIFIER
	AT_DH,					// DEST HIGH
	AT_DL,					// DEST LOW
	AT_DP,					// DISASSOCIATED SP

	AT_EA,					// ACK FAILURES
	AT_EC,					// CCA FAILURES
	AT_EE,					// AES ECRYPTION ENABLE

	AT_GT,					// GUART TIMES

	AT_HV,					// HARDWARE VERS

	AT_IA,					// IO INPUT ADDRESS
	AT_IC,					// DIO CHANGE DETECT
	AT_ID,					// PANID
	AT_IR,					// SAPLE RATE
	AT_IT,					// SAMPLES BEFORE TX
	AT_IU,					// IO OUTPUT ENABLE

	AT_KY,					// AES ECRYPTION KEY

	AT_MM,					// MAC MODE
	AT_MY,					// SHORT ADDR

	AT_NB,					// PARITY
	AT_NI,					// NODE IDENTIFY
	AT_NO,					// NODE DISCOVER OPTION
	AT_NT,					// NODE DISCOVER TIME

	AT_Rq,					// R?
	AT_RE,					// RESET
	AT_RN,					// RANDOM DELAY SLOTS
	AT_RO,					// PACKETIZATION TIMEOUT
	AT_RP,					// RSSI PWM TIMER
	AT_RR,					// XBEE RETRIES

	AT_P0,					// PWM0 CONFIGURATION
	AT_P1,					// PWM1 CONFIGURATION
	AT_PL,					// POWER LEVEL
	AT_PR,					// PULLUP RESISTOR ENABLE
	AT_PT,					// PWM OUTPUT TIMEOUT

	AT_SB,					// STOP BITS
	AT_SC,					// SCAN CHANNELS
	AT_SD,					// SCAN DURATION
	AT_SH,					// SERIAL HIGH
	AT_SL,					// SERIAL LOW
	AT_SM,					// SLEEP MODE
	AT_SO,					// SLEEP OPTION
	AT_SP,					// CYCLIC SLEEP PERIOD
	AT_SS,					// SLEEP STATUS
	AT_ST,					// TIME BEFORE SLEEP

	AT_T0,					// D0 OUTPUT TIMEOUT
	AT_T1,					// D1 OUTPUT TIMEOUT
	AT_T2,					// D2 OUTPUT TIMEOUT
	AT_T3,					// D3 OUTPUT TIMEOUT
	AT_T4,					// D4 OUTPUT TIMEOUT
	AT_T5,					// D5 OUTPUT TIMEOUT
	AT_T6,					// D6 OUTPUT TIMEOUT
	AT_T7,					// D7 OUTPUT TIMEOUT

	AT_VR,					// FIRMWARE VERS

	AT_WR,					// WRITE

	DE_FV,					// AT FIRMWARE VERSION

}__attribute__((packed)) cmdIDs;

#endif /* ENUM_CMD_H_ */